name: Export Issues to Excel

on:
  workflow_dispatch:

jobs:
  export-issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm config set registry https://registry.npmjs.org/
        npm install axios xlsx

    - name: Run export-issues script
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export GITHUB_TOKEN=$GITHUB_TOKEN
        node export.js

